/**
 * HomePage.tsx: the app home page.
 */

import { Container } from '@mui/system';
import { Alert } from '@mui/material';
import { AppBar, Typography } from '@zscreen/psychscreen-ui-components';
import { useNavigate } from 'react-router-dom';

const HomePage: React.FC = () => {
    const navigate = useNavigate();
    return (
        <>
            <AppBar
                onDownloadsClicked={() => navigate("/downloads")}
                onHomepageClicked={() => navigate("/")}
            />
            <Container style={{ marginTop: "5em", marginLeft: "6em", width: "40%" }}>
                <Typography
                    type="display"
                    size="medium"
                >
                    Explore the genetics and epigenetics of the human brain.
                </Typography>
                <div style={{ height: "2em" }} />
                <Typography
                    type="body"
                    size="large"
                >
                    PsychSCREEN integrates knowledge generated by the PsychENCODE Consortium with results from the broader scientific community.
                </Typography>
                <div style={{ height: "2em" }} />
                <Alert severity='info'>
                    <Typography
                        type="title"
                        size="large"
                    >
                        This page is in development.
                    </Typography>
                    <Typography
                        type="body"
                        size="medium"
                    >
                        Use the "downloads" link at the top right to download some analysis results, including a set of
                        brain-active cis-regulatory elements.
                    </Typography>
                </Alert>
            </Container>
        </>
    );
};
export default HomePage;
