/**
 * HomePage.tsx: the app home page.
 */

import { Container } from '@mui/system';
import { Alert, Grid } from '@mui/material';
import { AppBar, Typography } from '@zscreen/psychscreen-ui-components';
import { useNavigate } from 'react-router-dom';

import BRAIN from '../../assets/brain.png';

const HomePage: React.FC = () => {
    const navigate = useNavigate();
    return (
        <>
            <AppBar
                onDownloadsClicked={() => navigate("/downloads")}
                onHomepageClicked={() => navigate("/")}
            />
            <Grid container>
                <Grid item sm={1} />
                <Grid item sm={4}>
                    <Container style={{ marginTop: "5em" }}>
                        <Typography
                            type="display"
                            size="medium"
                        >
                            Explore the genetics and epigenetics of the human brain.
                        </Typography>
                        <div style={{ height: "2em" }} />
                        <Typography
                            type="body"
                            size="large"
                        >
                            PsychSCREEN integrates knowledge generated by the PsychENCODE Consortium with results from the broader scientific community.
                        </Typography>
                        <div style={{ height: "2em" }} />
                        <Alert severity='info'>
                            <Typography
                                type="title"
                                size="large"
                            >
                                This page is in development.
                            </Typography>
                            <Typography
                                type="body"
                                size="medium"
                            >
                                Use the "downloads" link at the top right to download some analysis results, including a set of
                                brain-active cis-regulatory elements.
                            </Typography>
                        </Alert>
                    </Container>
                </Grid>
                <Grid item sm={7}>
                    <img src={BRAIN} style={{ width: "50%" }} />
                </Grid>
            </Grid>
        </>
    );
};
export default HomePage;
